from typing import Protocol
from src.models import Ticket

class TicketConnector(Protocol):
    def list_tickets(self) -> list[Ticket]: ...
    def get_ticket(self, ticket_id: str) -> Ticket: ...
    def update_ticket(self, ticket_id: str, decision: str, note: str, validated: bool = False) -> Ticket: ...
