-- Generated synthetic fixtures; source: sample_data/tickets.json.
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1041','Account locked after password change','My domain account is locked on LAB-PC-014. I changed my password yesterday and Windows now says the account is locked out. One user affected.','Sam Ellis','Low','Medium','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1042','VPN authentication fails after password change','VPN client rejects authentication after a Windows password change. Home internet works. Alex Morgan cannot access the internal ERP from LAB-LT-042 and a delivery deadline is approaching.','Alex Morgan','Low','High','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1043','Internal portal hostname does not resolve','The operations department cannot resolve portal.northstar.example. Access by the approved test IP 192.0.2.20 works. All department users are affected; a workaround exists.','Robin Bell','Medium','Medium','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1044','Warehouse printer appears offline','LAB-PRN-003 is offline and shipping documents are stuck in the print queue. Four warehouse staff are affected. Labels are needed before the next dispatch.','Casey Stone','Medium','High','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1045','Windows 11 workstation is slow','LAB-PC-025 is slow when opening applications. Windows 11 reports low disk space after an update. Only one employee is affected and another workstation is available.','Jamie Park','Low','Low','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1046','Outlook repeatedly requests sign-in','Outlook on LAB-LT-018 repeatedly asks for Microsoft 365 sign-in. Outlook on the web works for Taylor Reed. No other users have reported the issue.','Taylor Reed','Low','Medium','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1047','Access denied to mapped finance drive','Jordan Lee receives Access denied on \\files.northstar.example\finance after a team move. Other network drives work. An authorized colleague can handle urgent requests.','Jordan Lee','Low','Medium','Open');
INSERT INTO tickets (id,title,description,requester,impact,urgency,status) VALUES ('INC-1048','ERP unavailable across all locations','The fictional Northstar Demo ERP returns HTTP 503 for all locations. Order processing has stopped and there is no workaround. Started at 09:15 UTC.','Morgan Blake','High','High','Open');
