-- Generated deterministic reviewed synthetic knowledge seed. No network calls.
PRAGMA foreign_keys=ON;
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-active-directory-account-lockout','Identity: Account lockout','runbook','Identity and access','Active Directory','Active Directory','Windows','en','approved','1.0','2026-09-11','["account lockout","authentication","password change"]','synthetic-demo','knowledge_base/active-directory.md','80f8fe08fa9d705dedecee24594a8f5f2fa7f657c76d9d98bb76d54bbf325250') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-active-directory-account-lockout';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-active-directory-account-lockout--00-identity-account-lockout','kb-active-directory-account-lockout','0','Identity: Account lockout','Portfolio knowledge article. Synthetic lab context; technician validation required.','cb89be873cdd1208daeb16d914bc4437f11e02e2d51f907d4b797e94b10a88c4');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-active-directory-account-lockout--01-symptoms','kb-active-directory-account-lockout','1','Symptoms','- active directory account locked repeated failed domain logon
- domain user locked out after password change
- windows sign in account lockout on domain controller
- directory authentication account disabled or locked
- cannot logon domain account says locked','d377fbdc7513ca1371671eba16892f53ee8059cd6f898206eb492fc569dc1a6c');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-active-directory-account-lockout--02-working-hypothesis','kb-active-directory-account-lockout','2','Working hypothesis','Directory authentication is blocked by a lockout; stale credentials are one possible source.','1c249b2a6d27de86e0a2dd1f7646e829261fd9124b322428586811defd4a0c26');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-active-directory-account-lockout--03-troubleshooting','kb-active-directory-account-lockout','3','Troubleshooting','1. Confirm user identity using the approved verification procedure; never request a password.
2. Ask the directory team to inspect lockout events and the originating device.
3. Check for stored credentials in scheduled tasks, mobile mail and mapped drives.
4. After identity verification, request an authorized unlock and update stale credentials.
5. Validate a fresh sign-in and monitor for repeated lockouts; escalate suspicious activity.','e6fd89fc9336c959bec3ec83b7e1cafc81a33d4b1adee28b942cf06e20dd598b');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-active-directory-account-lockout--04-escalation-and-closure','kb-active-directory-account-lockout','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-network-dns-troubleshooting','Network: DNS','runbook','Network','DNS','Corporate network',NULL,'en','approved','1.0','2026-09-11','["dns","hostname","name resolution"]','synthetic-demo','knowledge_base/dns-troubleshooting.md','71a19075b936770742eaa43415f02697740b30b10717a81d4454f16e7050c25d') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-network-dns-troubleshooting';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-dns-troubleshooting--00-network-dns','kb-network-dns-troubleshooting','0','Network: DNS','Portfolio knowledge article. Synthetic lab context; technician validation required.','995dc6d7d003967dfb9ba2f450d8afd559488b7da03f5efaaaf1fd6e28c984bd');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-dns-troubleshooting--01-symptoms','kb-network-dns-troubleshooting','1','Symptoms','- dns server not responding hostname lookup failure
- internal website name resolution fails but ip works
- cannot resolve intranet hostname dns record
- dns nxdomain on company network
- network connectivity dns lookup timeout','813a457e6afe4b46c8f5c561e1a25b8c2355eddeb371f8d74f8977e7fdd161c6');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-dns-troubleshooting--02-working-hypothesis','kb-network-dns-troubleshooting','2','Working hypothesis','An incorrect DNS server, stale cache or missing record may prevent name resolution.','a2dc7824626e8722c54ca9300a24b1f5fc65cc0c726d3510c8cc49ac63e99ee2');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-dns-troubleshooting--03-troubleshooting','kb-network-dns-troubleshooting','3','Troubleshooting','1. Confirm scope and record the affected hostname and exact error.
2. Compare connectivity by approved IP and hostname; ping failure alone does not prove an outage.
3. Inspect adapter and DNS configuration; use Resolve-DnsName against the configured resolver.
4. Compare with a working device; do not replace corporate DNS with public resolvers.
5. Consider an approved cache flush only when evidence supports it; escalate authoritative record or resolver faults.','4daceb94fc9a1423d3dbd2b1a3b6a959568a61a2cfb5b4bdd96fbe44612427c0');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-dns-troubleshooting--04-escalation-and-closure','kb-network-dns-troubleshooting','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-business-application-erp','Application: ERP','runbook','Business application','ERP','Northstar Demo ERP',NULL,'en','approved','1.0','2026-09-11','["erp","access","service unavailable"]','synthetic-demo','knowledge_base/erp-access.md','80aa405c9bec45724679178ed5d32bc6ec7fce1f5f9f5a6365a2ba9c0ad1c4cd') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-business-application-erp';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-business-application-erp--00-application-erp','kb-business-application-erp','0','Application: ERP','Portfolio knowledge article. Synthetic lab context; technician validation required.','5a835ab7566b61dbe4ef15bb5507b6ef2dfa1b1f3a0ac8fef80574894b84d35f');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-business-application-erp--01-symptoms','kb-business-application-erp','1','Symptoms','- erp application unavailable all users order entry
- enterprise resource planning login server error
- erp access denied application role
- business application erp service unavailable
- erp application returns 503 backend connection','240015102b12ce3b201c1b3e407335ca32b7ec3852d13fbd43443dea7c028fa2');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-business-application-erp--02-working-hypothesis','kb-business-application-erp','2','Working hypothesis','The ERP service, backend connectivity or application authorization may be failing.','4e91c0f2f493f72a263605c46c3e7f5a200076bb10a7a997014dafe20f5b5dd7');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-business-application-erp--03-troubleshooting','kb-business-application-erp','3','Troubleshooting','1. Capture the application error, timestamp and affected business workflow.
2. Confirm whether the issue affects multiple users and check the service status.
3. Test the approved application endpoint without collecting business records.
4. Gather sanitized correlation IDs and compare recent approved deployments.
5. Escalate to application support with impact and evidence; do not restart the database or change production records.','300c06d862a2d69271bd6fe5a3eb8057d1f16885582aa2990fa1aa218b70f038');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-business-application-erp--04-escalation-and-closure','kb-business-application-erp','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-service-desk-escalation-policy','Escalation and priority policy','policy','Service Desk','General','DeskPilot',NULL,'en','approved','1.0','2026-09-11','["escalation","priority","handover"]','synthetic-demo','knowledge_base/escalation-guidelines.md','ea9a48239ed4ce827d3fbde19f7f163d927b5f8d30760b9a2dbf419567cc6c6c') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-service-desk-escalation-policy';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-service-desk-escalation-policy--00-escalation-and-priority-policy','kb-service-desk-escalation-policy','0','Escalation and priority policy','This is an illustrative local policy, not a contracted SLA or an official ITIL matrix.
Impact: High = organization or multiple locations; Medium = department; Low = individual.
Urgency: High = work stopped with no viable workaround or imminent deadline; Medium = degraded work; Low = workaround available.

| Impact / Urgency | High | Medium | Low |
|---|---|---|---|
| High | P1 | P2 | P3 |
| Medium | P2 | P3 | P4 |
| Low | P3 | P4 | P4 |

Illustrative initial response targets: P1 15 minutes, P2 1 hour, P3 4 business hours, P4 1 business day.
The app displays targets only; it does not track SLA clocks or business calendars.
P1/P2 incidents require escalation. Low model evidence requires manual triage.
Suspected compromise requires security review. Never request passwords or MFA codes.
Record impact, timeline, symptoms, evidence and actions before handover. Do not close on a recommendation alone.','81fa7d0246fca861b04427a6509160ca2af04787b405d0489c94fad5b3f249db');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-microsoft365-outlook-authentication','Identity: Microsoft 365','runbook','Microsoft 365','Email','Microsoft 365',NULL,'en','approved','1.0','2026-09-11','["outlook","email","sign in"]','synthetic-demo','knowledge_base/microsoft365.md','9a5276008a8d5177e7a64276bc1b7dfac4ce494c28e57cc003a882817d824c6d') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-microsoft365-outlook-authentication';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-microsoft365-outlook-authentication--00-identity-microsoft-365','kb-microsoft365-outlook-authentication','0','Identity: Microsoft 365','Portfolio knowledge article. Synthetic lab context; technician validation required.','7aee5801d85e9a8e634776612b5d5111349598c3da424b78adbb63ddc3f61d8d');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-microsoft365-outlook-authentication--01-symptoms','kb-microsoft365-outlook-authentication','1','Symptoms','- outlook keeps asking password microsoft 365 login
- microsoft 365 mfa authentication sign in error
- outlook authentication loop office token expired
- office 365 mailbox cannot sign in
- outlook web access works desktop sign in fails','e14056157307e133cdb60953b6ca5559b822b13467c51583e838a6309a2e38a7');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-microsoft365-outlook-authentication--02-working-hypothesis','kb-microsoft365-outlook-authentication','2','Working hypothesis','An expired sign-in session or a tenant authentication policy may be interrupting Outlook access.','c1edf3606b08f927fbb52bb59ed50fe43a01354ce1208f8c88f56cb816ef07f7');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-microsoft365-outlook-authentication--03-troubleshooting','kb-microsoft365-outlook-authentication','3','Troubleshooting','1. Capture the error, sign-in time and whether Outlook on the web works.
2. Check Microsoft 365 service health through the authorized administrator.
3. Validate account, license and MFA status through approved support channels.
4. Try an approved sign-out and sign-in; preserve drafts and avoid deleting profiles prematurely.
5. Escalate Conditional Access or repeated authentication failures with correlation IDs, without tokens or passwords.','eb2d3d1a6294dc37d9d87a62695f5bb7d6dc2b6513e61ca84836a5a97864534c');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-microsoft365-outlook-authentication--04-escalation-and-closure','kb-microsoft365-outlook-authentication','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-access-shared-folder','Access: Shared folder','runbook','Identity and access','Permissions','SMB file share','Windows','en','approved','1.0','2026-09-11','["permissions","mapped drive","shared folder"]','synthetic-demo','knowledge_base/network-drive.md','ace9ce170b9c9e2cb92871c5332cdb3236656526ce994c52cdccf5f83aca62a1') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-access-shared-folder';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-access-shared-folder--00-access-shared-folder','kb-access-shared-folder','0','Access: Shared folder','Portfolio knowledge article. Synthetic lab context; technician validation required.','9032e877ab39addee279571469dedf2ae20a3bea7072d48dcc5c6635e977e2bc');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-access-shared-folder--01-symptoms','kb-access-shared-folder','1','Symptoms','- mapped network drive access denied shared folder
- smb file share permission denied unc path
- network drive disconnected file server access
- shared folder ntfs permissions cannot open
- mapped drive missing after login share access','87e84f1647f4f9cf36fac49986970e13e7a2e4d061e58815d9547956c535d0df');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-access-shared-folder--02-working-hypothesis','kb-access-shared-folder','2','Working hypothesis','An SMB session, group membership or share/NTFS permission mismatch may deny access.','e7f420a7511dcff0c4b9809b004545a74b92b0f83876a95a0f41167673b100d4');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-access-shared-folder--03-troubleshooting','kb-access-shared-folder','3','Troubleshooting','1. Capture the UNC path and error; confirm VPN or local network connectivity.
2. Check name resolution and connectivity to the approved file server.
3. Compare effective share and NTFS permissions with the documented entitlement.
4. Check recent group changes and reconnect the session after an approved sign-in refresh.
5. Request data-owner authorization for permission changes; never grant broad access as a shortcut.','c975fffe5ee20dd843f3f2fbccd5b2726784c00bde3b53fbf821cf663745c518');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-access-shared-folder--04-escalation-and-closure','kb-access-shared-folder','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-hardware-printing','Hardware: Printing','runbook','Printing','Printer','Network printer',NULL,'en','approved','1.0','2026-09-11','["printer","print queue","spooler"]','synthetic-demo','knowledge_base/printer-troubleshooting.md','e3f501346c121a201807c13c45d2ffb592feee278f6eae745c3bd7002adac4a3') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-hardware-printing';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-hardware-printing--00-hardware-printing','kb-hardware-printing','0','Hardware: Printing','Portfolio knowledge article. Synthetic lab context; technician validation required.','5bf6bbfc1bd320febd34df4cbf030a88408feaddee9779bb086d161edb2b7dd8');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-hardware-printing--01-symptoms','kb-hardware-printing','1','Symptoms','- printer offline cannot print documents queue stuck
- print spooler service stopped jobs pending
- network printer offline print queue error
- printing fails printer unavailable
- documents stuck in spooler printing queue','d9261d46bd350c64e6ecd312e01eaf1d5eaa22614b94b1b2902172584397bb3c');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-hardware-printing--02-working-hypothesis','kb-hardware-printing','2','Working hypothesis','The printer connection, queue or spooler may be unavailable; confirm which layer is failing.','0490eec522c36340d2338eb3017a1eb25806043f7cda14f56414ee3eab1d7bb1');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-hardware-printing--03-troubleshooting','kb-hardware-printing','3','Troubleshooting','1. Check printer power, display errors, paper and network connection.
2. Confirm whether one user or the entire printer queue is affected.
3. Check the configured printer port and queue status before changing settings.
4. Inspect Print Spooler status; record pending jobs before proposing a restart.
5. If approved, restart the spooler during an agreed window and print a test page; escalate hardware faults.','ab76ca84255517bf96c0a9831ba370611687fa8b63459e5b68b36b7494156aac');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-hardware-printing--04-escalation-and-closure','kb-hardware-printing','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-software-general-incidents','Software: General incident','runbook','Software','General software','Desktop application',NULL,'en','approved','1.0','2026-09-11','["application crash","software error","launch failure"]','synthetic-demo','knowledge_base/software-incidents.md','9dccfd0251b227dd53e6373156f118084350ac77d2c2e616fdc568389fefbd3b') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-software-general-incidents';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-software-general-incidents--00-software-general-incident','kb-software-general-incidents','0','Software: General incident','Portfolio knowledge article. Synthetic lab context; technician validation required.','9d82cca3ad23b7fb7101dca8f3116ce4dd3e4f2c789bf641ea56712abd0775d1');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-software-general-incidents--01-symptoms','kb-software-general-incidents','1','Symptoms','- desktop application crashes or will not launch
- software error after an approved update
- application freezes for one user
- general program installation or runtime failure','388e806cf9a39bf5c904533a7f2b86933f2dd188b1516ffe893a73cf6694bd4f');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-software-general-incidents--02-working-hypothesis','kb-software-general-incidents','2','Working hypothesis','A local application state, dependency, configuration, or recent approved change may be responsible.','25ffbbf79ac7ecf464a430f9a48971251154a32a73cf3e5f1a277dde4b505f06');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-software-general-incidents--03-troubleshooting','kb-software-general-incidents','3','Troubleshooting','1. Capture the exact error, application version, start time, and affected scope.
2. Confirm whether the same approved application works for another synthetic user or workstation.
3. Review recent approved changes and vendor support status without downloading unapproved tools.
4. Preserve user files and logs approved for support before proposing repair or reinstallation.
5. Validate recovery with the user; escalate repeat crashes, security indicators, or unsupported software.','db8ef91ae595f85c5cd610f9237fcbc20f90f0c0ad79613a70a922702cb1493a');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-software-general-incidents--04-escalation-and-closure','kb-software-general-incidents','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-network-vpn-troubleshooting','Network: VPN','runbook','Network','VPN','Corporate VPN',NULL,'en','approved','1.0','2026-09-11','["vpn","remote access","authentication"]','synthetic-demo','knowledge_base/vpn-troubleshooting.md','f0a57b581f4e89216e74e9d98b153583059bc10e4ba715dffed1d487845ffc83') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-network-vpn-troubleshooting';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-vpn-troubleshooting--00-network-vpn','kb-network-vpn-troubleshooting','0','Network: VPN','Portfolio knowledge article. Synthetic lab context; technician validation required.','58ddfc28f6a7bb972a8baf0291f7f93bd9606ac715bb4ee241f231bfa436f026');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-vpn-troubleshooting--01-symptoms','kb-network-vpn-troubleshooting','1','Symptoms','- vpn connection failed after changing password
- remote access vpn tunnel authentication rejected
- vpn client cannot connect gateway timeout
- vpn disconnect remote worker authentication error
- unable to establish corporate vpn tunnel','a85c6026d3ba60ded09cd706a9314b28446d7e062ecd3ffbf9b73d43a6c01a0c');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-vpn-troubleshooting--02-working-hypothesis','kb-network-vpn-troubleshooting','2','Working hypothesis','Saved VPN credentials or a client authentication state may be stale after a password change.','5ca6f3a1364311eb0e6e0ed5f6107dd9277cdb34e195a979593d12c47252055c');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-vpn-troubleshooting--03-troubleshooting','kb-network-vpn-troubleshooting','3','Troubleshooting','1. Confirm internet access before troubleshooting the VPN tunnel.
2. Capture the VPN error and time; verify the approved gateway and service status.
3. Validate account status and MFA through approved processes without sharing credentials.
4. Re-enter updated credentials in the approved client; do not disable MFA or certificate validation.
5. Reconnect and validate access to an approved internal resource; escalate persistent gateway failures.','833bcb7fb7101d2bdc67545b6317a45e5239fc005a6fc9273ee4d84139685a0d');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-network-vpn-troubleshooting--04-escalation-and-closure','kb-network-vpn-troubleshooting','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
INSERT INTO knowledge_documents(document_id,title,source_type,service,category,product,operating_system,language,approval_status,version,last_reviewed,tags_json,classification,source_path,content_hash) VALUES('kb-endpoint-windows-performance','Endpoint: Windows 11','runbook','Workstation','Performance','Windows 11','Windows 11','en','approved','1.0','2026-09-11','["windows","storage","performance"]','synthetic-demo','knowledge_base/windows-support.md','97940416a0f78b053d7fc8e3bd0651421a8668852e6663ec3d807e196558d347') ON CONFLICT(document_id) DO UPDATE SET title=excluded.title,source_type=excluded.source_type,service=excluded.service,category=excluded.category,product=excluded.product,operating_system=excluded.operating_system,language=excluded.language,approval_status=excluded.approval_status,version=excluded.version,last_reviewed=excluded.last_reviewed,tags_json=excluded.tags_json,classification=excluded.classification,source_path=excluded.source_path,content_hash=excluded.content_hash;
DELETE FROM knowledge_chunks WHERE document_id='kb-endpoint-windows-performance';
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-endpoint-windows-performance--00-endpoint-windows-11','kb-endpoint-windows-performance','0','Endpoint: Windows 11','Portfolio knowledge article. Synthetic lab context; technician validation required.','adb9db914b19a267161dbdc17b769e7ab478b60a060a39e0dce76333de1e0cbe');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-endpoint-windows-performance--01-symptoms','kb-endpoint-windows-performance','1','Symptoms','- windows 11 slow laptop disk full low space
- windows desktop freezing high cpu memory
- windows update error computer performance
- windows 11 crashes blue screen system
- computer running slow storage drive nearly full','305defcffe993a135953f9879cb1e7865b03a7aae4c872d48f3089fa4d022d2b');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-endpoint-windows-performance--02-working-hypothesis','kb-endpoint-windows-performance','2','Working hypothesis','Low disk space, a recent change or resource pressure may be causing Windows performance issues.','9c4b55cd1809f42fdbf39c02e0ff32ba743e03cb9ff580e4d6b32a58e22f54e1');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-endpoint-windows-performance--03-troubleshooting','kb-endpoint-windows-performance','3','Troubleshooting','1. Capture symptoms, start time and recent software or Windows updates.
2. Check free disk space, Task Manager and relevant Event Viewer entries.
3. Compare the impact before and after the recent change; preserve diagnostic evidence.
4. Use approved cleanup options after checking user data and backup status.
5. Validate performance with the user; escalate repeat crashes or suspected hardware faults.','19b899475218b67c5161b72719312eb51a27d8018ab7f184a82d53abed4e1357');
INSERT INTO knowledge_chunks(chunk_id,document_id,ordinal,heading,content,content_hash) VALUES('kb-endpoint-windows-performance--04-escalation-and-closure','kb-endpoint-windows-performance','4','Escalation and closure','Escalate when scope exceeds authorization, symptoms persist, or security indicators appear. Close only after user validation. Record evidence and outcome.','970b3d0e6ec4732b76d4634cfd6a7035ef379c06587f29a0cd10c4af904f7150');
